/**
 * API template
 * API template description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRoleDto } from './userRoleDto';


export interface UserDto { 
    id?: string;
    refreshToken?: string;
    username: string;
    lastname?: string;
    firstname?: string;
    password?: string;
    mail?: string;
    phone?: string;
    presentation?: string;
    creationDate?: Date;
    modifDate?: Date;
    roles?: Array<UserRoleDto>;
    rolesString?: Array<string>;
    disabled: boolean;
    initial?: string;
    imgUrl?: string;
}

